// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<apiKey>',
    appId: '1:618739543430:web:ecc5259ebc02932c429007',
    messagingSenderId: '618739543430',
    projectId: 'flash-chat-9f299',
    authDomain: 'flash-chat-9f299.firebaseapp.com',
    storageBucket: 'flash-chat-9f299.appspot.com',
    measurementId: 'G-4S3MNEDHLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '<apiKey>',
    appId: '1:618739543430:android:5e0a2f2ce98041ec429007',
    messagingSenderId: '618739543430',
    projectId: 'flash-chat-9f299',
    storageBucket: 'flash-chat-9f299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '<apiKey>',
    appId: '1:618739543430:ios:f62d49175601b9e8429007',
    messagingSenderId: '618739543430',
    projectId: 'flash-chat-9f299',
    storageBucket: 'flash-chat-9f299.appspot.com',
    iosClientId: '618739543430-vnhiokmmr15mdlk3e0naebi2sn8offk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '<apiKey>',
    appId: '1:618739543430:ios:8998afcc6c6d6e62429007',
    messagingSenderId: '618739543430',
    projectId: 'flash-chat-9f299',
    storageBucket: 'flash-chat-9f299.appspot.com',
    iosClientId: '618739543430-e13ce62j10fuomn4bs44lejkc6puirv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
